#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 1000					
#define WINDOW_HEIGHT 1080
#define WINDOW_TITLE "Victorio the game"

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define TILE_SIZE 32
#define MAP_WIDTH 100	
#define MAP_HEIGHT 100 

#define CLICK_COOLDOWN 1.0


// Terrain generation

#define SEED 27
#define NOISE_FREQ 0.02
#define NOISE_AMP 20

#define ORE_NOISE_FREQ 0.04
#define ORE_NOISE_AMP 2

#define TERRAIN_WATER_RANGE 40		// From 0 to 100
#define TERRAIN_SAND_RANGE 50
#define TERRAIN_GRASS_RANGE 70
#define TERRAIN_FORREST_RANGE 80
#define TERRAIN_ROCKY_RANGE 100

// Ore generation

#define IRON_ORE_RANGE 30
#define COPPER_ORE_RANGE 28
#define COAL_ORE_RANGE 18
#define STONE_ORE_RANGE 18

// Player

#define PLAYER_MAX_SPEED 400
#define PLAYER_MAX_INV_SIZE 100
#define PLAYER_START_INV_SIZE 10

#define PLAYER_DECONSTRUCT_SPEED 0.5




// Buildings

#define MAX_BUILDINGS 200

#define CRAFTER_MAX_INPUT 3
#define CRAFTER_MAX_OUTPUT 3
#define CRAFTER_WIDTH 3
#define CRAFTER_HEIGHT 3

#define MINER_WIDTH 2
#define MINER_HEIGHT 2

#define SMELTER_WIDTH 2
#define SMELTER_HEIGHT 2

#define INSERTER_WORK_TIME 1.0
#define CONVEYOR_WORK_TIME 0.3


// GUI
#define MAX_GUI_WINDOWS 5
#define MAX_GUI_FLAGS 5
#define MAX_GUI_CLASS 16
#define MAX_GUI_CLASS_MATHCHES 256
#define MAX_GUI_BUTTONS 128

#define GUI_TILE_SIZE 40
#define GUI_INVENTORY_WIDTH 10
#define GUI_INVENTORY_HEIGHT 10
#define GUI_TILE_MARGIN 2
#define GUI_RECIPE_WIDTH 7
#define GUI_RECIPE_HEIGHT 6

#define GUI_PADDING 16

#define GUI_SM_WIDTH 400
#define GUI_SM_HEIGHT 200


// Recipes and Crafting

#define MAX_RECIPES 128
#define MAX_ITEMS 128
#define CRAFT_METHODS 4
#define MAX_CRAFT_QUEUE 100



// Fonts
#define TEXT_SIZE 18


// Colors
#define COLOR_WHITE (SDL_Color){255, 255, 255, 255}
#define COLOR_BLACK (SDL_Color){0, 0, 0, 255}

#define COLOR_HEX_MAIN 0XFA9549FF 
#define COLOR_HEX_SEC 0X5F668CFF
#define COLOR_HEX_SEC_2 0X555b7eFF
#define COLOR_HEX_THIRD 0X393D54FF
#define COLOR_HEX_GREEN 0X668c5fFF